# Generated by Django 3.2.7 on 2021-11-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('officename', models.CharField(max_length=125)),
                ('attribution', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organizationname', models.CharField(max_length=125)),
                ('description', models.CharField(max_length=125)),
                ('datejoined', models.DateField(blank=True, default=None, null=True)),
                ('address1', models.CharField(max_length=125)),
                ('address2', models.CharField(blank=True, default=None, max_length=125, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=125, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=125, null=True)),
                ('zipcode', models.CharField(blank=True, default=None, max_length=125, null=True)),
                ('phonenumber', models.CharField(blank=True, default=None, max_length=125, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=125)),
                ('description', models.CharField(max_length=125)),
                ('premium', models.CharField(blank=True, default=None, max_length=125, null=True)),
                ('allocation', models.CharField(blank=True, default=None, max_length=125, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startdate', models.DateField()),
                ('servicecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synerD.service')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptiontypename', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=125, unique=True)),
                ('middlename', models.CharField(blank=True, default=None, max_length=125, null=True)),
                ('firstname', models.CharField(blank=True, default='None', max_length=125, null=True)),
                ('lastname', models.CharField(blank=True, default='None', max_length=125, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=125, null=True)),
                ('address1', models.CharField(blank=True, default=None, max_length=125, null=True)),
                ('address2', models.CharField(blank=True, default=None, max_length=125, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=125, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=125, null=True)),
                ('zipcode', models.CharField(blank=True, default=None, max_length=125, null=True)),
                ('employername', models.CharField(blank=True, default=None, max_length=125, null=True)),
                ('staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransferredSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferfrom', models.CharField(max_length=125)),
                ('transferto', models.CharField(max_length=125)),
                ('requestdate', models.DateField(blank=True, default=None, null=True)),
                ('transferdate', models.DateField(blank=True, default=None, null=True)),
                ('subscriberid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synerD.subscriber')),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscriptiontypecode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synerD.subscriptiontype'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synerD.userinfo'),
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField(blank=True, default=None, null=True)),
                ('nativecountry', models.CharField(blank=True, default=None, max_length=125, null=True)),
                ('citizenship', models.CharField(blank=True, default=None, max_length=125, null=True)),
                ('isdelegate', models.BooleanField()),
                ('organizationcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synerD.organization')),
                ('subscriberid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synerD.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('officecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synerD.office')),
                ('subscriberid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synerD.subscriber')),
            ],
        ),
    ]
