# Generated by Django 3.2.7 on 2021-11-24 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('synerD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='startdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
