# Generated by Django 3.2.7 on 2021-11-24 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synerD', '0003_alter_subscriber_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synerD.userinfo'),
        ),
    ]
