# Generated by Django 3.2.7 on 2021-11-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synerD', '0004_alter_subscriber_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address2',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='datejoined',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phonenumber',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='zipcode',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='citizenship',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='enddate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='nativecountry',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='allocation',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='premium',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='transferredsubscription',
            name='requestdate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transferredsubscription',
            name='transferdate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address1',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address2',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='employername',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='firstname',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='lastname',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='middlename',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='zipcode',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
    ]
