# Generated by Django 3.2.7 on 2021-11-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synerD', '0005_auto_20211124_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
